<?php
namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('mats')->insert(['name'=>'DI4Y Front Door Mat Welcome Mats - Entryway Mats for Shoe Scraper, Ideal for Inside Outside Home High Traffic Area Steel Gray 60x90cm','price'=>88.32,'sku'=>'B0C2DKVHY2','type'=>' welcome ','tags'=>'DI4Y,Front,Door,Mat,Welcome,Mats,-,Entryway,Mats,for,Shoe,Scraper,,Ideal,for,Inside,Outside,Home,High,Traffic,Area,Steel,Gray,60x90cm, welcome ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'YANAHUTE Original Durable Rubber Welcome Mat Heavy Duty Doormat for Indoor Outdoor Waterproof Easy Clean Low-Profile Rug Mats for Entry Patio High Traffic Areas Black Bird 20"x30"','price'=>87.38,'sku'=>'B0C2DKVHY1','type'=>' welcome ','tags'=>'YANAHUTE,Original,Durable,Rubber,Welcome,Mat,Heavy,Duty,Doormat,for,Indoor,Outdoor,Waterproof,Easy,Clean,Low-Profile,Rug,Mats,for,Entry,Patio,High,Traffic,Areas,Black,Bird,20"x30", welcome ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'YANAHUTE Original Durable Rubber Welcome Mat Heavy Duty Doormat for Indoor Outdoor Waterproof Easy Clean Low-Profile Rug Mats for Entry Patio High Traffic Areas Black Dragonfly 20"x30"','price'=>87.38,'sku'=>'B0C2DKVHY1','type'=>' welcome ','tags'=>'YANAHUTE,Original,Durable,Rubber,Welcome,Mat,Heavy,Duty,Doormat,for,Indoor,Outdoor,Waterproof,Easy,Clean,Low-Profile,Rug,Mats,for,Entry,Patio,High,Traffic,Areas,Black,Dragonfly,20"x30", welcome ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Large Door Mat Non Slip Outdoor Front Door Mat Super Absorb Mud Easy to Clean Black Tree of Life Doormat for Entrance Indoor Patio ','price'=>56.99,'sku'=>'B0BGLWZ32H','type'=>' welcome ','tags'=>'Large,Door,Mat,Non,Slip,Outdoor,Front,Door,Mat,Super,Absorb,Mud,Easy,to,Clean,Black,Tree,of,Life,Doormat,for,Entrance,Indoor,Patio,, welcome ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Large Door Mat Non Slip Outdoor Front Door Mat Super Absorb Mud Easy to Clean Brown Tree of Life Doormat for Entrance Indoor Patio ','price'=>56.99,'sku'=>'B0BGLWZ32H','type'=>' welcome ','tags'=>'Large,Door,Mat,Non,Slip,Outdoor,Front,Door,Mat,Super,Absorb,Mud,Easy,to,Clean,Brown,Tree,of,Life,Doormat,for,Entrance,Indoor,Patio,, welcome ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Memory Foam Bath Mat 2-Pack Non-Slip Back 40x60 cm Fleece Softness Highly Absorbent Bathroom Carpet Super Soft Microfiber Bath Rug Rectangle Easy to Clean Mat Grey','price'=>37.49,'sku'=>'B09FFFWY83','type'=>' bathroom ','tags'=>'Memory,Foam,Bath,Mat,2-Pack,Non-Slip,Back,40x60,cm,Fleece,Softness,Highly,Absorbent,Bathroom,Carpet,Super,Soft,Microfiber,Bath,Rug,Rectangle,Easy,to,Clean,Mat,Grey, bathroom ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Memory Foam Bath Mat 2-Pack Non-Slip Back 40x60 cm Fleece Softness Highly Absorbent Bathroom Carpet Super Soft Microfiber Bath Rug Rectangle Easy to Clean Mat Black','price'=>37.49,'sku'=>'B09FFFWY83','type'=>' bathroom ','tags'=>'Memory,Foam,Bath,Mat,2-Pack,Non-Slip,Back,40x60,cm,Fleece,Softness,Highly,Absorbent,Bathroom,Carpet,Super,Soft,Microfiber,Bath,Rug,Rectangle,Easy,to,Clean,Mat,Black, bathroom ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Natureva Home Stone Bath Mat Absorbing Water Instantly Made of Natural Diatomaceous Earth Fast-Drying & Non-Slip Surface Modern Stylish Bathroom Mats Design Flow Graphite ','price'=>120,'sku'=>'B0BPTSN4KF','type'=>' bathroom ','tags'=>'Natureva,Home,Stone,Bath,Mat,Absorbing,Water,Instantly,Made,of,Natural,Diatomaceous,Earth,Fast-Drying,&,Non-Slip,Surface,Modern,Stylish,Bathroom,Mats,Design,Flow,Graphite,, bathroom ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Natureva Home Stone Bath Mat Absorbing Water Instantly Made of Natural Diatomaceous Earth Fast-Drying & Non-Slip Surface Modern Stylish Bathroom Mats Design Flow Chalk ','price'=>120,'sku'=>'B0BPTSN4KF','type'=>' bathroom ','tags'=>'Natureva,Home,Stone,Bath,Mat,Absorbing,Water,Instantly,Made,of,Natural,Diatomaceous,Earth,Fast-Drying,&,Non-Slip,Surface,Modern,Stylish,Bathroom,Mats,Design,Flow,Chalk,, bathroom ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Multi Purpose Floor Mat for Indoor Cycling Cross Training 91.4x198.1 cm ','price'=>140.5,'sku'=>'B00PD9GHUA','type'=>' weight lifting ','tags'=>'Multi,Purpose,Floor,Mat,for,Indoor,Cycling,Cross,Training,91.4x198.1,cm,, weight lifting ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'adidas Training Mat ','price'=>103.53,'sku'=>'B08K86GZY6','type'=>' yoga ','tags'=>'adidas,Training,Mat,, yoga ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'1/2-Inch Extra Thick Exercise Yoga Black Mat','price'=>89.85,'sku'=>'B01LP0VBDI','type'=>' yoga ','tags'=>'1/2-Inch,Extra,Thick,Exercise,Yoga,Black,Mat, yoga ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'1/2-Inch Extra Thick Exercise Yoga Purple Mat','price'=>89.85,'sku'=>'B01LP0VBDI','type'=>' yoga ','tags'=>'1/2-Inch,Extra,Thick,Exercise,Yoga,Purple,Mat, yoga ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Large Yoga Mat 183x114cm 6mm Thick Extra Wide Workout Mat for Men and Women Yoga Mat Thick Exercise Mats for Home Workout Yoga Pilates Black 72"x 45"  6mm','price'=>101.99,'sku'=>'B0BVPWDGWY','type'=>' yoga ','tags'=>'Large,Yoga,Mat,183x114cm,6mm,Thick,Extra,Wide,Workout,Mat,for,Men,and,Women,Yoga,Mat,Thick,Exercise,Mats,for,Home,Workout,Yoga,Pilates,Black,72"x,45",,6mm, yoga ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Everfit Air Track 3X1M 10cm Thick Tumbling Airtrack Mat Inflatable Gymnastics Training Cheerleading Yoga Gym Professional Equipment Multi-Colored Rainbow ','price'=>176.23,'sku'=>'B093PG9WY9','type'=>' gymnastics ','tags'=>'Everfit,Air,Track,3X1M,10cm,Thick,Tumbling,Airtrack,Mat,Inflatable,Gymnastics,Training,Cheerleading,Yoga,Gym,Professional,Equipment,Multi-Colored,Rainbow,, gymnastics ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'RIDEO Premium Inflatable Air Track Gymnastics Tumbling Mat Incl Electric Pump Bag Pink ','price'=>244.4,'sku'=>'B0C3MS4SC3','type'=>' gymnastics ','tags'=>'RIDEO,Premium,Inflatable,Air,Track,Gymnastics,Tumbling,Mat,Incl,Electric,Pump,Bag,Pink,, gymnastics ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Super Large 300cmx120cm Gymnastics Folding Gym Yoga Exercise Mat Pink','price'=>224.93,'sku'=>'B08KSWK1CX','type'=>' gymnastics ','tags'=>'Super,Large,300cmx120cm,Gymnastics,Folding,Gym,Yoga,Exercise,Mat,Pink, gymnastics ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Super Large 300cmx120cm Gymnastics Folding Gym Yoga Exercise Mat Blue','price'=>224.93,'sku'=>'B08KSY6JWT','type'=>' gymnastics ','tags'=>'Super,Large,300cmx120cm,Gymnastics,Folding,Gym,Yoga,Exercise,Mat,Blue, gymnastics ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Folding Yoga Mat Gymnastics Floor Exercise Green Gym Mat 180X60X5cm ','price'=>67.43,'sku'=>'B08KSYYKRZ','type'=>' gymnastics ','tags'=>'Folding,Yoga,Mat,Gymnastics,Floor,Exercise,Green,Gym,Mat,180X60X5cm,, gymnastics ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Folding Yoga Mat Gymnastics Floor Exercise Red Gym Mat 180X60X5cm ','price'=>67.43,'sku'=>'B08KSYYKRZ','type'=>' gymnastics ','tags'=>'Folding,Yoga,Mat,Gymnastics,Floor,Exercise,Red,Gym,Mat,180X60X5cm,, gymnastics ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'YESDEX Kitchen Mats 2-PC Anti Fatigue Kitchen Rugs Mats Large Kitchen Comfort Mat Waterproof Non-Slip Standing Mats Kitchen Living Room Office Sink Laundry Garage 150x44CM 76x44CM','price'=>74.99,'sku'=>'B0C24LFPQR','type'=>' fatigue ','tags'=>'YESDEX,Kitchen,Mats,2-PC,Anti,Fatigue,Kitchen,Rugs,Mats,Large,Kitchen,Comfort,Mat,Waterproof,Non-Slip,Standing,Mats,Kitchen,Living,Room,Office,Sink,Laundry,Garage,150x44CM,76x44CM, fatigue ','description'=>'The anti-fatigue mat provides an extra large area for standing in laundy room, kitchen, office, farmhouse, in from of sink or any other high traffic space.It offers cushioned support to massage your feet and to help relieve pressure on feet and knees.','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Kitchen Rugs and Mats 12mm Thick Anti Fatigue Waterproof Kitchen Office Garage Non Skid Standing Kitchen Rug 2 Piece 44x75cm Black','price'=>79.49,'sku'=>'B0BB2G5QR6','type'=>' fatigue ','tags'=>'Kitchen,Rugs,and,Mats,12mm,Thick,Anti,Fatigue,Waterproof,Kitchen,Office,Garage,Non,Skid,Standing,Kitchen,Rug,2,Piece,44x75cm,Black, fatigue ','description'=>'Its innovative design features a stain-resistant surface, which means the mat will retains its like-new appearance when something like oil and peanut butter splash suddendly.To clean the kitchen comfort mat, simply wipe it down with soap and water as needed. kitchen mat has a non-slip bottom to ensure that the mat will stay in place for added safety and stability. This anti-fatigue comfort mat can be used on various floor surfaces. Step onto the mat, barefoot or in slippers or shoes, and youll feel how it quickly conforms to the contours of your feet.','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Standing Desk Mat Balance Board Anti Fatigue Wobble Floor Mat Wooden Ergonomics Comfort Standing Board Massage Foot Rocking Chair Balance with Hand Pull Rope Exercise for Home & Office','price'=>125.99,'sku'=>'B09YC9NPSF','type'=>' fatigue ','tags'=>'Standing,Desk,Mat,Balance,Board,Anti,Fatigue,Wobble,Floor,Mat,Wooden,Ergonomics,Comfort,Standing,Board,Massage,Foot,Rocking,Chair,Balance,with,Hand,Pull,Rope,Exercise,for,Home,&,Office, fatigue ','description'=>'Each stability rocker is made with wooden board, an anti-slip pure PU layer to keep feet in place, and an anti-fatigue surface. pressure points gently massage away soreness to keep feet. Our standing balance board slides under your desk at home or at work to let you tilt, lean, and remain steady with an 8.5° tilting angle.  feeling energized','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Exercise Mat with EVA Foam  Black Interlocking Tiles for Weight Lifting','price'=>103.87,'sku'=>'B0719BJB14','type'=>' weight lifting ','tags'=>'Exercise,Mat,with,EVA,Foam,,Black,Interlocking,Tiles,for,Weight,Lifting, weight lifting ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Exercise Mat with EVA Foam  Black Interlocking Tiles for Weight Lifting','price'=>103.87,'sku'=>'B0719BJB15 ','type'=>' weight lifting ','tags'=>'Exercise,Mat,with,EVA,Foam,,Black,Interlocking,Tiles,for,Weight,Lifting, weight lifting ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'MotionTex Exercise Equipment Mat for Under Treadmill, Rowing Machine, Elliptical Machine, Fitness Equipment, Home Gym Floor Protection, 30" x 66", Black ','price'=>134.37,'sku'=>'B07D18GYTT','type'=>' weight lifting ','tags'=>'MotionTex,Exercise,Equipment,Mat,for,Under,Treadmill,,Rowing,Machine,,Elliptical,Machine,,Fitness,Equipment,,Home,Gym,Floor,Protection,,30",x,66",,Black,, weight lifting ','description'=>'Protect flat pile carpet & hard floors with MotionTex fitness equipment mats. Protect flooring from the damage, noise, and vibration caused by home workout equipment including stationary bikes, spin bikes, rowing machines, treadmills, steppers, elliptical machines, or other home gym items. MotionTex heavy-duty exercise equipment mat fits under most home fitness machines including Peloton, Echelon, Nordic Track, ProForm, and Bowflex gym equipment. Improve safety with the slip resistant top texture and rounded corners that reduce tripping hazards from curled mat edges while working out at home. Recycled PVC provides a non-absorbent surface that repels water, sweat, grease, and other liquids. Easily clean with soap and water or wipe with a cloth and household cleaner. ','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Exercise Equipment Mat,Treadmill Mat, Exercise Bike Mat, Fitness Mat, Elliptical Mat, rowing machine mat,Recumbent Bikes,Jump Rope Mat, Gym Mat Use on Hardwood Floors Protection ','price'=>74.88,'sku'=>'B09BVBQSZ2','type'=>' weight lifting ','tags'=>'Exercise,Equipment,Mat,Treadmill,Mat,,Exercise,Bike,Mat,,Fitness,Mat,,Elliptical,Mat,,rowing,machine,mat,Recumbent,Bikes,Jump,Rope,Mat,,Gym,Mat,Use,on,Hardwood,Floors,Protection,, weight lifting ','description'=>'Exercise Equipment Mat - Treadmill Mat, Exercise Bike Mat, Fitness Mat, Elliptical Mat, Jump Rope Mat, Yoga Mat, Gym Mat Use on Hardwood Floors Protection','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Carfit 4541001 Protecta Carpet Car Floor Mat 4 Piece Set Black Set of 2 ','price'=>70.94,'sku'=>'B07GC22ZXT','type'=>' vehicle ','tags'=>'Carfit,4541001,Protecta,Carpet,Car,Floor,Mat,4,Piece,Set,Black,Set,of,2,, vehicle ','description'=>'Car fit Protecta Car Mat synonymous with the highest quality and performance and protection of your vehicle. Quality carpet with non-slip nibbed backing and heel pad protection. This long-term wear mat gives the great appearance. Not only look great and make cleaning your interior a breeze, they will also effectively prevent permanent damage to the interior of your vehicle. Non fading, non delaminating and non tearing qualities will give you years of reliable motoring protection. Available in black colour. Set includes 2 front and 2 rear car mats. Front mat measures 45 cm width by 66 cm height. Rear mat measures 44 cm width by 33 cm height.','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'3-Piece Premium Rubber Floor Mat for Cars SUVs and Trucks All Vehicle Weather Protection Universal Trim to Fit Black','price'=>97.86,'sku'=>'B07TXB64W5','type'=>' vehicle ','tags'=>'3-Piece,Premium,Rubber,Floor,Mat,for,Cars,SUVs,and,Trucks,All,Vehicle,Weather,Protection,Universal,Trim,to,Fit,Black, vehicle ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'3-Piece Premium Rubber Floor Mat for Cars SUVs and Trucks All Vehicle Weather Protection Universal Trim to Fit Grey','price'=>97.86,'sku'=>'B07TXB64W5','type'=>' vehicle ','tags'=>'3-Piece,Premium,Rubber,Floor,Mat,for,Cars,SUVs,and,Trucks,All,Vehicle,Weather,Protection,Universal,Trim,to,Fit,Grey, vehicle ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'4 Pieces Car Floor Mats,Daisy Butterfly Dragonfly Mushroom Automotive Mats,Rubber Non-Slip Floor Mats Car Vehicle Decor Accessories Fit for SUV Van Truck Car','price'=>105.08,'sku'=>'B09K5B4Y7X','type'=>' vehicle ','tags'=>'4,Pieces,Car,Floor,Mats,Daisy,Butterfly,Dragonfly,Mushroom,Automotive,Mats,Rubber,Non-Slip,Floor,Mats,Car,Vehicle,Decor,Accessories,Fit,for,SUV,Van,Truck,Car, vehicle ','description'=>'High quality thick soft polyester material,Non-fading , Non-Skid Rubber Backing with black edges to ensure a secure grip.Helps to protect your vehicle interior floor from Dirt, mud, dust, and any other elements. Universal fit for most SUV, Sedan, Trucks, Van etc. ','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Xyiafc 4 Pcs Car Mats Rock and Roll Skull Rock and Roll Skull Car Floor Mats for Women Rubber Non-Slip Floor Mats for Cars Daughter Gift from Mom Dad, (Xyiafc-4) ','price'=>121.25,'sku'=>'B09L6411J8','type'=>' vehicle ','tags'=>'Xyiafc,4,Pcs,Car,Mats,Rock,and,Roll,Skull,Rock,and,Roll,Skull,Car,Floor,Mats,for,Women,Rubber,Non-Slip,Floor,Mats,for,Cars,Daughter,Gift,from,Mom,Dad,,(Xyiafc-4),, vehicle ','description'=>'About Car Decoration Accessories Introduction:All our products are produced by our own factory. We have a wide range of car decoration accessories.All Weather Car Floor MatsUniversal Car Floor Mats?2front mats - 14.8*26.8inch 2rear mats - 14.8*26.8inch-Soft polyester surface can comfortably support your feet.-Non slip rubber nibs on the bottom keep the mats not move.-Always keep your vehicle interior clean,enjoy a pleased driving day with personalized mats.-Please check dimensions before installation,any question please feel free to contact us.Material:Hight quality thick soft polyester material,Non-fading , Non-Skid Rubber Backing with black edges to ensure a secure grip.Helps to protect your vehicle interior floor from Dirt, mud, dust, and any other elementsOccasion: Universal fit for most SUV, Sedan, Trucks, Van etcChoose The Right floor mats for cars, Enjoy Your Journey!','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Xyiafc 4 Pcs Car Mats Trippy Mushroom Car Floor Mats for Women Rubber Non-Slip Vehicle Floor Mats for Cars Daughter Gift from Mom Dad','price'=>121.25,'sku'=>'B09K5B4Y7X','type'=>' vehicle ','tags'=>'Xyiafc,4,Pcs,Car,Mats,Trippy,Mushroom,Car,Floor,Mats,for,Women,Rubber,Non-Slip,Vehicle,Floor,Mats,for,Cars,Daughter,Gift,from,Mom,Dad, vehicle ','description'=>'About Car Decoration Accessories Introduction:All our products are produced by our own factory. We have a wide range of car decoration accessories.All Weather Car Floor MatsUniversal Car Floor Mats?2front mats - 14.8*26.8inch 2rear mats - 14.8*26.8inch-Soft polyester surface can comfortably support your feet.-Non slip rubber nibs on the bottom keep the mats not move.-Always keep your vehicle interior clean,enjoy a pleased driving day with personalized mats.-Please check dimensions before installation,any question please feel free to contact us.Material:Hight quality thick soft polyester material,Non-fading , Non-Skid Rubber Backing with black edges to ensure a secure grip.Helps to protect your vehicle interior floor from Dirt, mud, dust, and any other elementsOccasion: Universal fit for most SUV, Sedan, Trucks, Van etcChoose The Right floor mats for cars, Enjoy Your Journey!','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'SENDAY Placemats, Set of 8 Heat-Resistant Placemats Stain Resistant Anti-Skid Placemats for Kitchen Table Washable Durable PVC Table Mats Woven Vinyl Beige Placemat','price'=>67.43,'sku'=>'B0878WQJTY','type'=>' placemat ','tags'=>'SENDAY,Placemats,,Set,of,8,Heat-Resistant,Placemats,Stain,Resistant,Anti-Skid,Placemats,for,Kitchen,Table,Washable,Durable,PVC,Table,Mats,Woven,Vinyl,Beige,Placemat, placemat ','description'=>'Placemats may seem like a frivolous extra when setting the table, but they actually serve a functional purpose as well as aesthetic. PVC material does not absorb water, so it is easy to rinse with water and dry quickly. –Both indoors and outdoors suitable for, but not limited to restaurants, cafes, desks, living rooms, coffee tables etc. Even you can use it in the drawer of the table.','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'SENDAY Placemats, Set of 8 Heat-Resistant Placemats Stain Resistant Anti-Skid Placemats for Kitchen Table Washable Durable PVC Table Mats Woven Vinyl Black Placemat','price'=>67.43,'sku'=>'B0878WQJTY','type'=>' placemat ','tags'=>'SENDAY,Placemats,,Set,of,8,Heat-Resistant,Placemats,Stain,Resistant,Anti-Skid,Placemats,for,Kitchen,Table,Washable,Durable,PVC,Table,Mats,Woven,Vinyl,Black,Placemat, placemat ','description'=>'Placemats may seem like a frivolous extra when setting the table, but they actually serve a functional purpose as well as aesthetic. PVC material does not absorb water, so it is easy to rinse with water and dry quickly. –Both indoors and outdoors suitable for, but not limited to restaurants, cafes, desks, living rooms, coffee tables etc. Even you can use it in the drawer of the table.','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'SENDAY Placemats, Set of 8 Heat-Resistant Placemats Stain Resistant Anti-Skid Placemats for Kitchen Table Washable Durable PVC Table Mats Woven Vinyl Blue Placemat','price'=>67.43,'sku'=>'B0878WQJTY','type'=>' placemat ','tags'=>'SENDAY,Placemats,,Set,of,8,Heat-Resistant,Placemats,Stain,Resistant,Anti-Skid,Placemats,for,Kitchen,Table,Washable,Durable,PVC,Table,Mats,Woven,Vinyl,Blue,Placemat, placemat ','description'=>'Placemats may seem like a frivolous extra when setting the table, but they actually serve a functional purpose as well as aesthetic. PVC material does not absorb water, so it is easy to rinse with water and dry quickly. –Both indoors and outdoors suitable for, but not limited to restaurants, cafes, desks, living rooms, coffee tables etc. Even you can use it in the drawer of the table.','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'SENDAY Placemats, Set of 8 Heat-Resistant Placemats Stain Resistant Anti-Skid Placemats for Kitchen Table Washable Durable PVC Table Mats Woven Vinyl Red Placemat','price'=>67.43,'sku'=>'B0878WQJTY','type'=>' placemat ','tags'=>'SENDAY,Placemats,,Set,of,8,Heat-Resistant,Placemats,Stain,Resistant,Anti-Skid,Placemats,for,Kitchen,Table,Washable,Durable,PVC,Table,Mats,Woven,Vinyl,Red,Placemat, placemat ','description'=>'Placemats may seem like a frivolous extra when setting the table, but they actually serve a functional purpose as well as aesthetic. PVC material does not absorb water, so it is easy to rinse with water and dry quickly. –Both indoors and outdoors suitable for, but not limited to restaurants, cafes, desks, living rooms, coffee tables etc. Even you can use it in the drawer of the table.','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Cinnamon Dubai Placemats 6-Pieces Set 34x26.5cm Multicolor','price'=>67.43,'sku'=>'B07P69R8PZ','type'=>' placemat ','tags'=>'Cinnamon,Dubai,Placemats,6-Pieces,Set,34x26.5cm,Multicolor, placemat ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Maxwell Williams Royal Botanic Gardens Australian Botanics Cork Back Placemat 34x26.5cm Set of 4 Assorted Gift Boxed ','price'=>59.93,'sku'=>'B08WR4MR8L','type'=>' placemat ','tags'=>'Maxwell,Williams,Royal,Botanic,Gardens,Australian,Botanics,Cork,Back,Placemat,34x26.5cm,Set,of,4,Assorted,Gift,Boxed,, placemat ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Heopapin Blacklight Astronaut Jellyfish Tapestry Trippy Mushroom Tapestry UV Reactive Fantasy Plants Wall Tapestry Psychedelic Neon Galaxy Space Tapestry Wall Hanging for Room W78×H59 ','price'=>43.48,'sku'=>'B0B5XG27N8','type'=>' tapestry ','tags'=>'Heopapin,Blacklight,Astronaut,Jellyfish,Tapestry,Trippy,Mushroom,Tapestry,UV,Reactive,Fantasy,Plants,Wall,Tapestry,Psychedelic,Neon,Galaxy,Space,Tapestry,Wall,Hanging,for,Room,W78×H59,, tapestry ','description'=>'The Blacklight Astronaut Tapestry Home Decoration Is Great for Dorm Room, Apartment, Bedroom,Living Room and More.This blacklight Astronaut Jellyfish tapestry looks colourful both under blacklight/UV light or not.  Durable and stretch material, washable and reusable. ','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'THE ART BOX Tapestry Green Tree of Life Wall Hanging Psychedelic Tapestries Indian Cotton Twin Bedspread Picnic Sheet Wall Decor Blanket Wall Art Hippie Bedroom Décor Medium 60x54 Inch','price'=>47.99,'sku'=>'B08XJQZY68','type'=>' tapestry ','tags'=>'THE,ART,BOX,Tapestry,Green,Tree,of,Life,Wall,Hanging,Psychedelic,Tapestries,Indian,Cotton,Twin,Bedspread,Picnic,Sheet,Wall,Decor,Blanket,Wall,Art,Hippie,Bedroom,Décor,Medium,60x54,Inch, tapestry ','description'=>'These sheets are made in Jaipur, India . These beautiful bedspreads or Tapestry are screen printed on cotton cloth by using traditional Rajasthani methods . They are perfect to be used as bed sheet or Tapestry . # Each bedspread / throw is beautifully screen printed with beautiful patterns colors. # Bright colors add vibrancy to your living space / bedroom. # Made in Non smoking environment This gorgeous piece of art can be used as: -Tapestry or a Wall Hanging. -Bedspread -Bed Cover -Table Cloth -Curtain - Dorm Decor - Picnic Sheet','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'THE ART BOX Tapestry Turquoise Tree of Life Wall Hanging Psychedelic Tapestries Indian Cotton Twin Bedspread Picnic Sheet Wall Decor Blanket Wall Art Hippie Bedroom Décor Medium 60"x54"','price'=>47.99,'sku'=>'B08XJQZY69','type'=>' tapestry ','tags'=>'THE,ART,BOX,Tapestry,Turquoise,Tree,of,Life,Wall,Hanging,Psychedelic,Tapestries,Indian,Cotton,Twin,Bedspread,Picnic,Sheet,Wall,Decor,Blanket,Wall,Art,Hippie,Bedroom,Décor,Medium,60"x54", tapestry ','description'=>'These sheets are made in Jaipur, India . These beautiful bedspreads or Tapestry are screen printed on cotton cloth by using traditional Rajasthani methods . They are perfect to be used as bed sheet or Tapestry . # Each bedspread / throw is beautifully screen printed with beautiful patterns colors. # Bright colors add vibrancy to your living space / bedroom. # Made in Non smoking environment This gorgeous piece of art can be used as: -Tapestry or a Wall Hanging. -Bedspread -Bed Cover -Table Cloth -Curtain - Dorm Decor - Picnic Sheet','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'THE ART BOX Tapestry Purple Tree of Life Wall Hanging Psychedelic Tapestries Indian Cotton Twin Bedspread Picnic Sheet Wall Decor Blanket Wall Art Hippie Bedroom Décor Medium 60"x54"','price'=>49.49,'sku'=>'B08XJQZY70','type'=>' tapestry ','tags'=>'THE,ART,BOX,Tapestry,Purple,Tree,of,Life,Wall,Hanging,Psychedelic,Tapestries,Indian,Cotton,Twin,Bedspread,Picnic,Sheet,Wall,Decor,Blanket,Wall,Art,Hippie,Bedroom,Décor,Medium,60"x54", tapestry ','description'=>'These sheets are made in Jaipur, India . These beautiful bedspreads or Tapestry are screen printed on cotton cloth by using traditional Rajasthani methods . They are perfect to be used as bed sheet or Tapestry . # Each bedspread / throw is beautifully screen printed with beautiful patterns colors. # Bright colors add vibrancy to your living space / bedroom. # Made in Non smoking environment This gorgeous piece of art can be used as: -Tapestry or a Wall Hanging. -Bedspread -Bed Cover -Table Cloth -Curtain - Dorm Decor - Picnic Sheet','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Meagtlva Black Light Alien Tapestry Wall Hanging Mushroom Tapestry UFO Tapestry  Alien Poster UV Light Tapestry for Bedroom 59"×79"','price'=>49.49,'sku'=>'B0BVLKK2G4','type'=>' tapestry ','tags'=>'Meagtlva,Black,Light,Alien,Tapestry,Wall,Hanging,Mushroom,Tapestry,UFO,Tapestry,,Alien,Poster,UV,Light,Tapestry,for,Bedroom,59"×79", tapestry ','description'=>'These trippy alien tapestry featuring vivid colors and crisp lines, it will add a sense of mysterious and eye-catching for your room. No strange odor. Toxic free and safe. Never worry about fading.','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Meagtlva Black Light Alien Tapestry Wall Hanging Mushroom Tapestry UFO Tapestry  Alien Poster UV Light Tapestry for Bedroom 59"×79"','price'=>49.49,'sku'=>'B0BVLKK2G4','type'=>' tapestry ','tags'=>'Meagtlva,Black,Light,Alien,Tapestry,Wall,Hanging,Mushroom,Tapestry,UFO,Tapestry,,Alien,Poster,UV,Light,Tapestry,for,Bedroom,59"×79", tapestry ','description'=>'These trippy alien tapestry featuring vivid colors and crisp lines, it will add a sense of mysterious and eye-catching for your room. No strange odor. Toxic free and safe. Never worry about fading.','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Acupressure Mat Yoga Massage Sit Lying Pain Stress Relax Blue 130 x 50cm','price'=>53.99,'sku'=>'MAT1002-BL','type'=>'yoga','tags'=>'Acupressure,Mat,Yoga,Massage,Sit,Lying,Pain,Stress,Relax,Blue,130,x,50cm,yoga','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Acupressure Mat Yoga Massage Sit Lying Pain Stress Relax Black 130 x 50cm','price'=>53.99,'sku'=>'MAT1002-BK','type'=>'yoga','tags'=>'Acupressure,Mat,Yoga,Massage,Sit,Lying,Pain,Stress,Relax,Black,130,x,50cm,yoga','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Acupressure Mat Yoga Massage Sit Lying Pain Stress Relax Blue 68 x 42cm','price'=>35.09,'sku'=>'MAT1001-BL','type'=>'yoga','tags'=>'Acupressure,Mat,Yoga,Massage,Sit,Lying,Pain,Stress,Relax,Blue,68,x,42cm,yoga','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Acupressure Mat Yoga Massage Sit Lying Pain Stress Relax Black 68 x 42cm','price'=>35.09,'sku'=>'MAT1002-BK','type'=>'yoga','tags'=>'Acupressure,Mat,Yoga,Massage,Sit,Lying,Pain,Stress,Relax,Black,68,x,42cm,yoga','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow 10X Artificial Grass Floor Tile Garden Indoor Outdoor Lawn Home Decor','price'=>80.99,'sku'=>'SG1026-NT-10','type'=>'outdoor ','tags'=>'Marlow,10X,Artificial,Grass,Floor,Tile,Garden,Indoor,Outdoor,Lawn,Home,Decor,outdoor ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow 20X Artificial Grass Floor Tile Garden Indoor Outdoor Lawn Home Decor','price'=>148.49,'sku'=>'SG1026-NT-20','type'=>'outdoor ','tags'=>'Marlow,20X,Artificial,Grass,Floor,Tile,Garden,Indoor,Outdoor,Lawn,Home,Decor,outdoor ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow 30X Artificial Grass Floor Tile Garden Indoor Outdoor Lawn Home Decor','price'=>215.99,'sku'=>'SG1026-NT-30','type'=>'outdoor ','tags'=>'Marlow,30X,Artificial,Grass,Floor,Tile,Garden,Indoor,Outdoor,Lawn,Home,Decor,outdoor ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Bathroom Mats Floor Mat Bath Anti Slip Toilet Carpet Meomory Foam Large Grey','price'=>28.34,'sku'=>'HO0563-GY','type'=>'bath ','tags'=>'Bathroom,Mats,Floor,Mat,Bath,Anti,Slip,Toilet,Carpet,Meomory,Foam,Large,Grey,bath ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Bath Mat Anti Slip Bathroom Shower Mat Thick Soft Fast Drying 160 x 50 cm','price'=>26.99,'sku'=>'HO0563-CF','type'=>'bath ','tags'=>'Bath,Mat,Anti,Slip,Bathroom,Shower,Mat,Thick,Soft,Fast,Drying,160,x,50,cm,bath ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'BoPeep Baby Play Mat EVA Kids Crawling Pad Floor Child Rug Play Carpet 36PCS','price'=>67.49,'sku'=>'KD1104-9PCSx4','type'=>'kids ','tags'=>'BoPeep,Baby,Play,Mat,EVA,Kids,Crawling,Pad,Floor,Child,Rug,Play,Carpet,36PCS,kids ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'BoPeep Baby Play Mat EVA Kids Crawling Pad Floor Child Rug Play Carpet 36PCS','price'=>67.49,'sku'=>'KD1103-9PCSx4','type'=>'kids ','tags'=>'BoPeep,Baby,Play,Mat,EVA,Kids,Crawling,Pad,Floor,Child,Rug,Play,Carpet,36PCS,kids ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'BoPeep Kids Play Mat Baby Crawling Pad Floor Foldable XPE Foam Non-slip Bear','price'=>64.79,'sku'=>'KD1039','type'=>' kids ','tags'=>'BoPeep,Kids,Play,Mat,Baby,Crawling,Pad,Floor,Foldable,XPE,Foam,Non-slip,Bear, kids ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'BoPeep Kids Play Mat Baby Crawling Pad Floor Foldable XPE Foam Non-slip Star','price'=>64.79,'sku'=>'KD1037','type'=>' kids ','tags'=>'BoPeep,Kids,Play,Mat,Baby,Crawling,Pad,Floor,Foldable,XPE,Foam,Non-slip,Star, kids ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'BoPeep Kids Play Mat Baby Crawling Pad Floor Foldable XPE Foam Non-slip Cloud','price'=>64.79,'sku'=>'KD1036','type'=>' kids ','tags'=>'BoPeep,Kids,Play,Mat,Baby,Crawling,Pad,Floor,Foldable,XPE,Foam,Non-slip,Cloud, kids ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'BoPeep Kids Play Mat Baby Crawling Pad Floor Foldable XPE Foam Non-slip Carpet','price'=>71.54,'sku'=>'KD1075','type'=>' kids ','tags'=>'BoPeep,Kids,Play,Mat,Baby,Crawling,Pad,Floor,Foldable,XPE,Foam,Non-slip,Carpet, kids ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'BoPeep Kids Play Mat Baby Crawling Pad Floor Foldable XPE Foam Non-slip Carpet','price'=>71.54,'sku'=>'KD1074','type'=>' kids ','tags'=>'BoPeep,Kids,Play,Mat,Baby,Crawling,Pad,Floor,Foldable,XPE,Foam,Non-slip,Carpet, kids ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'BoPeep Kids Play Mat Baby Crawling Pad Floor Foldable XPE Foam Non-slip Carpet','price'=>71.54,'sku'=>'KD1073','type'=>' kids ','tags'=>'BoPeep,Kids,Play,Mat,Baby,Crawling,Pad,Floor,Foldable,XPE,Foam,Non-slip,Carpet, kids ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'BoPeep Baby Play Mat EVA Kids Crawling Pad Floor Child Rug Play Foam Carpet 9PCS','price'=>24.29,'sku'=>'KD1104-9PCS','type'=>' kids ','tags'=>'BoPeep,Baby,Play,Mat,EVA,Kids,Crawling,Pad,Floor,Child,Rug,Play,Foam,Carpet,9PCS, kids ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'BoPeep Baby Play Mat EVA Kids Crawling Pad Floor Child Rug Play Foam Carpet 9PCS','price'=>26.99,'sku'=>'KD1103-9PCS','type'=>' kids ','tags'=>'BoPeep,Baby,Play,Mat,EVA,Kids,Crawling,Pad,Floor,Child,Rug,Play,Foam,Carpet,9PCS, kids ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Oribel waterproof Splat Mat','price'=>79.65,'sku'=>'OR219-90006','type'=>' kids ','tags'=>'Oribel,waterproof,Splat,Mat, kids ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Chair Mat Carpet Hard Floor Protectors PVC Home Office Room Computer Work Mats Black','price'=>45.89,'sku'=>'E0045-BK','type'=>' office ','tags'=>'Chair,Mat,Carpet,Hard,Floor,Protectors,PVC,Home,Office,Room,Computer,Work,Mats,Black, office ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Chair Mat Carpet Hard Floor Protectors Home Office Room Computer Work PVC Mats Black','price'=>60.74,'sku'=>'T4463-BK','type'=>' office ','tags'=>'Chair,Mat,Carpet,Hard,Floor,Protectors,Home,Office,Room,Computer,Work,PVC,Mats,Black, office ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Chair Mat Carpet Hard Floor Protectors Home Office Room Computer Work PVC Mats No Pin','price'=>53.99,'sku'=>'T4463-NOPIN','type'=>' office ','tags'=>'Chair,Mat,Carpet,Hard,Floor,Protectors,Home,Office,Room,Computer,Work,PVC,Mats,No,Pin, office ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Chair Mat Carpet Hard Floor Protectors Home Office Room Computer Work PVC Mats No Pin Black','price'=>44.54,'sku'=>'T4463-NOPIN-BK','type'=>' office ','tags'=>'Chair,Mat,Carpet,Hard,Floor,Protectors,Home,Office,Room,Computer,Work,PVC,Mats,No,Pin,Black, office ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Chair Mat Round Carpet Protectors PVC Home Office Room Computer Mats','price'=>56.69,'sku'=>'T0120','type'=>' office ','tags'=>'Marlow,Chair,Mat,Round,Carpet,Protectors,PVC,Home,Office,Room,Computer,Mats, office ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Chair Mat Round Carpet Protectors PVC Home Office Room Computer Mats','price'=>56.69,'sku'=>'T0120-BK','type'=>' office ','tags'=>'Marlow,Chair,Mat,Round,Carpet,Protectors,PVC,Home,Office,Room,Computer,Mats, office ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Chair Mat Round Carpet Protectors PVC Home Office Room Computer Mats','price'=>45.89,'sku'=>'E0045-SQ-NOPIN-BK','type'=>' office ','tags'=>'Marlow,Chair,Mat,Round,Carpet,Protectors,PVC,Home,Office,Room,Computer,Mats, office ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Chair Mat Round Carpet Protectors PVC Home Office Room Computer Mats','price'=>47.24,'sku'=>'E0045-SQ','type'=>' office ','tags'=>'Marlow,Chair,Mat,Round,Carpet,Protectors,PVC,Home,Office,Room,Computer,Mats, office ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Chair Mat Round Carpet Protectors PVC Home Office Room Computer Mats','price'=>47.24,'sku'=>'E0045-SQ-BK','type'=>' office ','tags'=>'Marlow,Chair,Mat,Round,Carpet,Protectors,PVC,Home,Office,Room,Computer,Mats, office ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Anti Fatigue Mat Standing Desk Rug Kitchen Home Office Foam Grey 50x80','price'=>53.99,'sku'=>'DH1043-M-GY','type'=>' office ','tags'=>'Marlow,Anti,Fatigue,Mat,Standing,Desk,Rug,Kitchen,Home,Office,Foam,Grey,50x80, office ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Anti Fatigue Mat Standing Desk Rug Kitchen Home Office Foam Black 50x80','price'=>53.99,'sku'=>'DH1043-M-BK','type'=>' office ','tags'=>'Marlow,Anti,Fatigue,Mat,Standing,Desk,Rug,Kitchen,Home,Office,Foam,Black,50x80, office ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Anti Fatigue Mat Standing Desk Rug Kitchen Home Office Foam Black 51x99','price'=>58.04,'sku'=>'DH1043-L-BK','type'=>' office ','tags'=>'Marlow,Anti,Fatigue,Mat,Standing,Desk,Rug,Kitchen,Home,Office,Foam,Black,51x99, office ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Carpet Floor Office Home Computer Work Chair Mats Vinyl PVC Plastic 1350x1140mm','price'=>53.99,'sku'=>'T4463','type'=>' office ','tags'=>'Carpet,Floor,Office,Home,Computer,Work,Chair,Mats,Vinyl,PVC,Plastic,1350x1140mm, office ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Floor Mat Rugs Shaggy Rug Area Carpet Large Soft Mats 300x200cm Tan','price'=>87.74,'sku'=>'E0044-300x200-TA','type'=>' rugs ','tags'=>'Marlow,Floor,Mat,Rugs,Shaggy,Rug,Area,Carpet,Large,Soft,Mats,300x200cm,Tan, rugs ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Floor Mat Rugs Shaggy Rug Area Carpet Large Soft Mats 300x200cm Cream','price'=>81.89,'sku'=>'E0044-300x200-CR','type'=>' rugs ','tags'=>'Marlow,Floor,Mat,Rugs,Shaggy,Rug,Area,Carpet,Large,Soft,Mats,300x200cm,Cream, rugs ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Floor Mat Rugs Shaggy Rug Area Carpet Large Soft Mats 300x200cm Purple','price'=>81.89,'sku'=>'E0044-300x200-PR','type'=>' rugs ','tags'=>'Marlow,Floor,Mat,Rugs,Shaggy,Rug,Area,Carpet,Large,Soft,Mats,300x200cm,Purple, rugs ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Floor Mat Rugs Shaggy Rug Large Area Carpet Bedroom Living Room 50x80cm','price'=>24.29,'sku'=>'FR2011-50x80','type'=>' rugs ','tags'=>'Marlow,Floor,Mat,Rugs,Shaggy,Rug,Large,Area,Carpet,Bedroom,Living,Room,50x80cm, rugs ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Floor Mat Rugs Shaggy Rug Large Area Carpet Bedroom Living Room 50x80cm','price'=>29.69,'sku'=>'FR2010-50x80','type'=>' rugs ','tags'=>'Marlow,Floor,Mat,Rugs,Shaggy,Rug,Large,Area,Carpet,Bedroom,Living,Room,50x80cm, rugs ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Floor Mat Rugs Shaggy Rug Large Area Carpet Bedroom Living Room 50x80cm','price'=>24.29,'sku'=>'FR2009-50x80','type'=>' rugs ','tags'=>'Marlow,Floor,Mat,Rugs,Shaggy,Rug,Large,Area,Carpet,Bedroom,Living,Room,50x80cm, rugs ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Floor Mat Rugs Shaggy Rug Large Area Carpet Bedroom Living Room 50x80cm','price'=>24.29,'sku'=>'FR2008-50x80','type'=>' rugs ','tags'=>'Marlow,Floor,Mat,Rugs,Shaggy,Rug,Large,Area,Carpet,Bedroom,Living,Room,50x80cm, rugs ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Floor Mat Rugs Shaggy Rug Large Area Carpet Bedroom Living Room 50x80cm','price'=>24.29,'sku'=>'FR2007-50x80','type'=>' rugs ','tags'=>'Marlow,Floor,Mat,Rugs,Shaggy,Rug,Large,Area,Carpet,Bedroom,Living,Room,50x80cm, rugs ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Floor Mat Rugs Shaggy Rug Large Area Carpet Bedroom Living Room 50x80cm','price'=>24.29,'sku'=>'FR2006-50x80','type'=>' rugs ','tags'=>'Marlow,Floor,Mat,Rugs,Shaggy,Rug,Large,Area,Carpet,Bedroom,Living,Room,50x80cm, rugs ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Floor Mat Rugs Shaggy Rug Area Carpet Large Soft Mats 300x200cm Burgundy','price'=>81.89,'sku'=>'E0044-300x200-BG','type'=>' rugs ','tags'=>'Marlow,Floor,Mat,Rugs,Shaggy,Rug,Area,Carpet,Large,Soft,Mats,300x200cm,Burgundy, rugs ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Marlow Floor Mat Rugs Shaggy Rug Large Area Carpet Bedroom Living Room 200x290cm','price'=>102.95,'sku'=>'FR2006-200x290','type'=>' rugs ','tags'=>'Marlow,Floor,Mat,Rugs,Shaggy,Rug,Large,Area,Carpet,Bedroom,Living,Room,200x290cm, rugs ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'PaWz Dog Mat Pet Calming Bed Memory Foam Orthopedic Removable Cover Washable M','price'=>53.99,'sku'=>'PT1139-M-GN','type'=>' pets ','tags'=>'PaWz,Dog,Mat,Pet,Calming,Bed,Memory,Foam,Orthopedic,Removable,Cover,Washable,M, pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'PaWz Dog Mat Pet Calming Bed Memory Foam Orthopedic Removable Cover Washable M','price'=>53.99,'sku'=>'PT1139-M-CF','type'=>' pets ','tags'=>'PaWz,Dog,Mat,Pet,Calming,Bed,Memory,Foam,Orthopedic,Removable,Cover,Washable,M, pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'PaWz Dog Mat Pet Calming Bed Memory Foam Orthopedic Removable Cover Washable M','price'=>53.99,'sku'=>'PT1139-M-CH','type'=>' pets ','tags'=>'PaWz,Dog,Mat,Pet,Calming,Bed,Memory,Foam,Orthopedic,Removable,Cover,Washable,M, pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'PaWz Dog Mat Pet Calming Bed Memory Foam Orthopedic Removable Cover Washable XL','price'=>89.09,'sku'=>'PT1139-XL-GN','type'=>'pets ','tags'=>'PaWz,Dog,Mat,Pet,Calming,Bed,Memory,Foam,Orthopedic,Removable,Cover,Washable,XL,pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'PaWz Dog Mat Pet Calming Bed Memory Foam Orthopedic Removable Cover Washable XL','price'=>89.09,'sku'=>'PT1139-XL-CF','type'=>' pets ','tags'=>'PaWz,Dog,Mat,Pet,Calming,Bed,Memory,Foam,Orthopedic,Removable,Cover,Washable,XL, pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'PaWz Dog Mat Pet Calming Bed Memory Foam Orthopedic Removable Cover Washable XL','price'=>89.09,'sku'=>'T1139-XL-CH','type'=>' pets ','tags'=>'PaWz,Dog,Mat,Pet,Calming,Bed,Memory,Foam,Orthopedic,Removable,Cover,Washable,XL, pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'PaWz Pet Bed Mattress Dog Cat Pad Mat Cushion Soft Winter Warm 2X Large Blue','price'=>64.79,'sku'=>'E0060-XXL-BL','type'=>' pets ','tags'=>'PaWz,Pet,Bed,Mattress,Dog,Cat,Pad,Mat,Cushion,Soft,Winter,Warm,2X,Large,Blue, pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'PaWz Pet Bed Mattress Dog Cat Pad Mat Cushion Soft Winter Warm 2X Large Cream','price'=>64.79,'sku'=>'E0060-XXL-CR','type'=>' pets ','tags'=>'PaWz,Pet,Bed,Mattress,Dog,Cat,Pad,Mat,Cushion,Soft,Winter,Warm,2X,Large,Cream, pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'PaWz Pet Bed Mattress Dog Cat Pad Mat Puppy Cushion Soft Warm Washable XL Grey','price'=>65.09,'sku'=>'JC1008-XL-GY','type'=>' pets ','tags'=>'PaWz,Pet,Bed,Mattress,Dog,Cat,Pad,Mat,Puppy,Cushion,Soft,Warm,Washable,XL,Grey, pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'PaWz Pet Bed Mattress Dog Cat Pad Mat Puppy Cushion Soft Warm Washable XL Blue','price'=>62.09,'sku'=>'JC1008-XL-BL','type'=>' pets ','tags'=>'PaWz,Pet,Bed,Mattress,Dog,Cat,Pad,Mat,Puppy,Cushion,Soft,Warm,Washable,XL,Blue, pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'PaWz Pet Cooling Mat Gel Mats Bed Cool Pad Puppy Cat Non-Toxic Beds 40x30cm','price'=>25.64,'sku'=>'T4477-40x30','type'=>' pets ','tags'=>'PaWz,Pet,Cooling,Mat,Gel,Mats,Bed,Cool,Pad,Puppy,Cat,Non-Toxic,Beds,40x30cm, pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'PaWz Pet Cooling Mat Cat Dog Gel Non-Toxic Bed Pillow Sofa Self-cool Summer L','price'=>53.99,'sku'=>'PT1164-L','type'=>' pets ','tags'=>'PaWz,Pet,Cooling,Mat,Cat,Dog,Gel,Non-Toxic,Bed,Pillow,Sofa,Self-cool,Summer,L, pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'PaWz Pet Cooling Mat Cat Dog Gel Non-Toxic Bed Pillow Sofa Self-cool Summer L','price'=>48.59,'sku'=>'PT1163-L','type'=>' pets ','tags'=>'PaWz,Pet,Cooling,Mat,Cat,Dog,Gel,Non-Toxic,Bed,Pillow,Sofa,Self-cool,Summer,L, pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'PaWz Pet Cool Gel Mat Cat Bed Dog Bolster Waterproof Self-cooling Pads Summer L','price'=>76.94,'sku'=>'PT1112-L','type'=>' pets ','tags'=>'PaWz,Pet,Cool,Gel,Mat,Cat,Bed,Dog,Bolster,Waterproof,Self-cooling,Pads,Summer,L, pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'PaWz Pet Cool Gel Mat Cat Bed Dog Bolster Waterproof Self-cooling Pads Summer L','price'=>80.99,'sku'=>'PT1111-L','type'=>' pets ','tags'=>'PaWz,Pet,Cool,Gel,Mat,Cat,Bed,Dog,Bolster,Waterproof,Self-cooling,Pads,Summer,L, pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'PaWz Pet Cool Gel Mat Cat Bed Dog Bolster Waterproof Self-cooling Pads Summer L','price'=>80.99,'sku'=>'PT1110-L','type'=>' pets ','tags'=>'PaWz,Pet,Cool,Gel,Mat,Cat,Bed,Dog,Bolster,Waterproof,Self-cooling,Pads,Summer,L, pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Pet Bed Cat Dog Donut Nest Calming Mat Soft Plush Kennel Teal XL','price'=>93.14,'sku'=>'PT1035-XL-TL','type'=>' pets ','tags'=>'Pet,Bed,Cat,Dog,Donut,Nest,Calming,Mat,Soft,Plush,Kennel,Teal,XL, pets ','description'=>'','rating'=>1,'available'=>true]);
        DB::table('mats')->insert(['name'=>'Pet Bed Cat Dog Donut Nest Calming Mat Soft Plush Kennel Pink XL','price'=>93.14,'sku'=>'PT1035-XL-PK','type'=>' pets ','tags'=>'Pet,Bed,Cat,Dog,Donut,Nest,Calming,Mat,Soft,Plush,Kennel,Pink,XL, pets ','description'=>'','rating'=>1,'available'=>true]);

    }
}
